/**
 * Event types for AutoMaker event system
 */

export type EventType =
  | 'agent:stream'
  | 'auto-mode:event'
  | 'auto-mode:started'
  | 'auto-mode:stopped'
  | 'auto-mode:idle'
  | 'auto-mode:error'
  | 'feature:started'
  | 'feature:completed'
  | 'feature:stopped'
  | 'feature:error'
  | 'feature:progress'
  | 'feature:tool-use'
  | 'feature:follow-up-started'
  | 'feature:follow-up-completed'
  | 'feature:verified'
  | 'feature:committed'
  | 'project:analysis-started'
  | 'project:analysis-progress'
  | 'project:analysis-completed'
  | 'project:analysis-error'
  | 'suggestions:event'
  | 'spec-regeneration:event'
  // GitHub poller events
  | 'github-poller:started'
  | 'github-poller:stopped'
  | 'github-poller:poll-complete'
  | 'github-poller:poll-error'
  | 'github-poller:issue-claimed'
  // Orchestrator events
  | 'orchestrator:started'
  | 'orchestrator:stopped'
  | 'orchestrator:poll'
  | 'orchestrator:error'
  | 'orchestrator:research-started'
  | 'orchestrator:research-completed'
  | 'orchestrator:task-created'
  | 'orchestrator:task-updated'
  | 'orchestrator:state-changed'
  | 'orchestrator:invalid-transition'
  | 'orchestrator:validation-failed'
  | 'orchestrator:pr-created'
  | 'orchestrator:pr-comment-analysis'
  | 'orchestrator:phase-changed'
  | 'orchestrator:workspace-started'
  | 'orchestrator:workspace-failed'
  // MCP bridge events
  | 'mcp:tool-call'
  | 'mcp:tool-success'
  | 'mcp:tool-error'
  // Review watcher events
  | 'review-watcher:started'
  | 'review-watcher:stopped'
  | 'review-watcher:error'
  | 'review-watcher:task-found'
  | 'review-watcher:task-status'
  | 'review-watcher:task-approved'
  | 'review-watcher:iteration-started'
  | 'review-watcher:task-escalated'
  // Agent monitor events
  | 'agent-monitor:started'
  | 'agent-monitor:stopped'
  | 'agent-monitor:error'
  | 'agent-monitor:agent-registered'
  | 'agent-monitor:agent-unregistered'
  | 'agent-monitor:agent-status-changed'
  | 'agent-monitor:agent-crashed'
  | 'agent-monitor:high-resource-usage'
  | 'agent-monitor:orphans-cleaned'
  // Telemetry events
  | 'telemetry:started'
  | 'telemetry:stopped'
  | 'telemetry:provider-request'
  | 'telemetry:task-started'
  | 'telemetry:task-ended'
  | 'telemetry:tool-call'
  | 'telemetry:task-error'
  | 'telemetry:aggregated'
  // Shared state events
  | 'shared-state:changed'
  | 'shared-state:cleared'
  | 'shared-state:transaction-committed'
  | 'shared-state:transaction-rolledback'
  // Beads events (HYBRID-M2)
  | 'beads:issue-created'
  | 'beads:issue-updated'
  | 'beads:issue-deleted'
  | 'beads:dependency-added'
  | 'beads:dependency-removed'
  | 'beads:epic-started'
  | 'beads:epic-completed'
  | 'beads:sync-started'
  | 'beads:sync-completed'
  | 'beads:sync-error'
  | 'beads:task-ready'
  | 'beads:task-blocked'
  | 'beads:cross-feature-resolved'
  | 'beads:agent-assigned'
  | 'beads:agent-completed'
  | 'beads:agent-failed'
  | 'beads:agent-cleaned'
  | 'beads:helper-spawned'
  | 'beads:helper-completed'
  | 'beads:helper-failed';

export type EventCallback = (type: EventType, payload: unknown) => void;
